apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllYcG5iMjFsZWpwZ1kydHlYM0JoZEY5alVsZk9VM050Ykc1SlZXZGpjbk5LZVcxUlNrZFRoaGhpVjFVPSIKCQl9Cgl9Cn0=
